// DO NOT EDIT. generated by github.com/tinywasm/ormc

package clinical_encounter

import (
	"github.com/tinywasm/model"
	"github.com/tinywasm/orm"
)

type MedicalHistory struct {
	Id string
	PatientId string
	DoctorId string
	ReservationId string
	Status string
	AttentionAt int64
	Reason string
	Diagnostic string
	Prescription string
	Cie10Code string
	StartedAt int64
	FinishedAt int64
	PatientNameSnapshot string
	PatientRutSnapshot string
	DoctorNameSnapshot string
	DoctorSpecialtySnapshot string
	UpdatedAt int64
}

func (m *MedicalHistory) ModelName() string { return "medical_history" }

func (m *MedicalHistory) Schema() []model.Field { return MedicalHistoryModel.Fields }

func (m *MedicalHistory) Pointers() []any { return []any{&m.Id, &m.PatientId, &m.DoctorId, &m.ReservationId, &m.Status, &m.AttentionAt, &m.Reason, &m.Diagnostic, &m.Prescription, &m.Cie10Code, &m.StartedAt, &m.FinishedAt, &m.PatientNameSnapshot, &m.PatientRutSnapshot, &m.DoctorNameSnapshot, &m.DoctorSpecialtySnapshot, &m.UpdatedAt} }

func (m *MedicalHistory) IsNil() bool { return m == nil }

func (m *MedicalHistory) EncodeFields(w model.FieldWriter) {
	w.String("id", m.Id)
	w.String("patient_id", m.PatientId)
	w.String("doctor_id", m.DoctorId)
	w.String("reservation_id", m.ReservationId)
	w.String("status", m.Status)
	w.Int("attention_at", m.AttentionAt)
	w.String("reason", m.Reason)
	w.String("diagnostic", m.Diagnostic)
	w.String("prescription", m.Prescription)
	w.String("cie10_code", m.Cie10Code)
	w.Int("started_at", m.StartedAt)
	w.Int("finished_at", m.FinishedAt)
	w.String("patient_name_snapshot", m.PatientNameSnapshot)
	w.String("patient_rut_snapshot", m.PatientRutSnapshot)
	w.String("doctor_name_snapshot", m.DoctorNameSnapshot)
	w.String("doctor_specialty_snapshot", m.DoctorSpecialtySnapshot)
	w.Int("updated_at", m.UpdatedAt)
}

func (m *MedicalHistory) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok { m.Id = v }
	if v, ok := r.String("patient_id"); ok { m.PatientId = v }
	if v, ok := r.String("doctor_id"); ok { m.DoctorId = v }
	if v, ok := r.String("reservation_id"); ok { m.ReservationId = v }
	if v, ok := r.String("status"); ok { m.Status = v }
	if v, ok := r.Int("attention_at"); ok { m.AttentionAt = v }
	if v, ok := r.String("reason"); ok { m.Reason = v }
	if v, ok := r.String("diagnostic"); ok { m.Diagnostic = v }
	if v, ok := r.String("prescription"); ok { m.Prescription = v }
	if v, ok := r.String("cie10_code"); ok { m.Cie10Code = v }
	if v, ok := r.Int("started_at"); ok { m.StartedAt = v }
	if v, ok := r.Int("finished_at"); ok { m.FinishedAt = v }
	if v, ok := r.String("patient_name_snapshot"); ok { m.PatientNameSnapshot = v }
	if v, ok := r.String("patient_rut_snapshot"); ok { m.PatientRutSnapshot = v }
	if v, ok := r.String("doctor_name_snapshot"); ok { m.DoctorNameSnapshot = v }
	if v, ok := r.String("doctor_specialty_snapshot"); ok { m.DoctorSpecialtySnapshot = v }
	if v, ok := r.Int("updated_at"); ok { m.UpdatedAt = v }
}

type MedicalHistoryList []*MedicalHistory

func (s *MedicalHistoryList) Schema() []model.Field { return nil }
func (s *MedicalHistoryList) Pointers() []any     { return nil }
func (s *MedicalHistoryList) Len() int             { return len(*s) }
func (s *MedicalHistoryList) At(i int) model.Fielder { return (*s)[i] }
func (s *MedicalHistoryList) Append() model.Fielder  { v := &MedicalHistory{}; *s = append(*s, v); return v }
func (s *MedicalHistoryList) IsNil() bool          { return s == nil }
func (s *MedicalHistoryList) EncodeFields(_ model.FieldWriter) {}
func (s *MedicalHistoryList) DecodeFields(_ model.FieldReader) {}

func (m *MedicalHistory) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var MedicalHistory_ = struct {
	Id string
	PatientId string
	DoctorId string
	ReservationId string
	Status string
	AttentionAt string
	Reason string
	Diagnostic string
	Prescription string
	Cie10Code string
	StartedAt string
	FinishedAt string
	PatientNameSnapshot string
	PatientRutSnapshot string
	DoctorNameSnapshot string
	DoctorSpecialtySnapshot string
	UpdatedAt string
}{
	Id: "id",
	PatientId: "patient_id",
	DoctorId: "doctor_id",
	ReservationId: "reservation_id",
	Status: "status",
	AttentionAt: "attention_at",
	Reason: "reason",
	Diagnostic: "diagnostic",
	Prescription: "prescription",
	Cie10Code: "cie10_code",
	StartedAt: "started_at",
	FinishedAt: "finished_at",
	PatientNameSnapshot: "patient_name_snapshot",
	PatientRutSnapshot: "patient_rut_snapshot",
	DoctorNameSnapshot: "doctor_name_snapshot",
	DoctorSpecialtySnapshot: "doctor_specialty_snapshot",
	UpdatedAt: "updated_at",
}

func ReadOneMedicalHistory(qb *orm.QB, model *MedicalHistory) (*MedicalHistory, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllMedicalHistory(qb *orm.QB) (MedicalHistoryList, error) {
	var results MedicalHistoryList
	err := qb.ReadAll(
		func() model.Model { return &MedicalHistory{} },
		func(m model.Model) { results = append(results, m.(*MedicalHistory)) },
	)
	return results, err
}

type CreateVisitArgs struct {
	PatientId string
	DoctorId string
	AttentionAt int64
	Reason string
	PatientNameSnapshot string
	PatientRutSnapshot string
	DoctorNameSnapshot string
	ReservationId string
	Diagnostic string
	Prescription string
	DoctorSpecialtySnapshot string
}

func (m *CreateVisitArgs) ModelName() string { return "create_visit_args" }

func (m *CreateVisitArgs) Schema() []model.Field { return CreateVisitArgsModel.Fields }

func (m *CreateVisitArgs) Pointers() []any { return []any{&m.PatientId, &m.DoctorId, &m.AttentionAt, &m.Reason, &m.PatientNameSnapshot, &m.PatientRutSnapshot, &m.DoctorNameSnapshot, &m.ReservationId, &m.Diagnostic, &m.Prescription, &m.DoctorSpecialtySnapshot} }

func (m *CreateVisitArgs) IsNil() bool { return m == nil }

func (m *CreateVisitArgs) EncodeFields(w model.FieldWriter) {
	w.String("patient_id", m.PatientId)
	w.String("doctor_id", m.DoctorId)
	w.Int("attention_at", m.AttentionAt)
	w.String("reason", m.Reason)
	w.String("patient_name_snapshot", m.PatientNameSnapshot)
	w.String("patient_rut_snapshot", m.PatientRutSnapshot)
	w.String("doctor_name_snapshot", m.DoctorNameSnapshot)
	w.String("reservation_id", m.ReservationId)
	w.String("diagnostic", m.Diagnostic)
	w.String("prescription", m.Prescription)
	w.String("doctor_specialty_snapshot", m.DoctorSpecialtySnapshot)
}

func (m *CreateVisitArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("patient_id"); ok { m.PatientId = v }
	if v, ok := r.String("doctor_id"); ok { m.DoctorId = v }
	if v, ok := r.Int("attention_at"); ok { m.AttentionAt = v }
	if v, ok := r.String("reason"); ok { m.Reason = v }
	if v, ok := r.String("patient_name_snapshot"); ok { m.PatientNameSnapshot = v }
	if v, ok := r.String("patient_rut_snapshot"); ok { m.PatientRutSnapshot = v }
	if v, ok := r.String("doctor_name_snapshot"); ok { m.DoctorNameSnapshot = v }
	if v, ok := r.String("reservation_id"); ok { m.ReservationId = v }
	if v, ok := r.String("diagnostic"); ok { m.Diagnostic = v }
	if v, ok := r.String("prescription"); ok { m.Prescription = v }
	if v, ok := r.String("doctor_specialty_snapshot"); ok { m.DoctorSpecialtySnapshot = v }
}

type CreateVisitArgsList []*CreateVisitArgs

func (s *CreateVisitArgsList) Schema() []model.Field { return nil }
func (s *CreateVisitArgsList) Pointers() []any     { return nil }
func (s *CreateVisitArgsList) Len() int             { return len(*s) }
func (s *CreateVisitArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *CreateVisitArgsList) Append() model.Fielder  { v := &CreateVisitArgs{}; *s = append(*s, v); return v }
func (s *CreateVisitArgsList) IsNil() bool          { return s == nil }
func (s *CreateVisitArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *CreateVisitArgsList) DecodeFields(_ model.FieldReader) {}

func (m *CreateVisitArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type GetVisitArgs struct {
	Id string
}

func (m *GetVisitArgs) ModelName() string { return "get_visit_args" }

func (m *GetVisitArgs) Schema() []model.Field { return GetVisitArgsModel.Fields }

func (m *GetVisitArgs) Pointers() []any { return []any{&m.Id} }

func (m *GetVisitArgs) IsNil() bool { return m == nil }

func (m *GetVisitArgs) EncodeFields(w model.FieldWriter) {
	w.String("id", m.Id)
}

func (m *GetVisitArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok { m.Id = v }
}

type GetVisitArgsList []*GetVisitArgs

func (s *GetVisitArgsList) Schema() []model.Field { return nil }
func (s *GetVisitArgsList) Pointers() []any     { return nil }
func (s *GetVisitArgsList) Len() int             { return len(*s) }
func (s *GetVisitArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *GetVisitArgsList) Append() model.Fielder  { v := &GetVisitArgs{}; *s = append(*s, v); return v }
func (s *GetVisitArgsList) IsNil() bool          { return s == nil }
func (s *GetVisitArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *GetVisitArgsList) DecodeFields(_ model.FieldReader) {}

func (m *GetVisitArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type ListVisitsArgs struct {
	PatientId string
}

func (m *ListVisitsArgs) ModelName() string { return "list_visits_args" }

func (m *ListVisitsArgs) Schema() []model.Field { return ListVisitsArgsModel.Fields }

func (m *ListVisitsArgs) Pointers() []any { return []any{&m.PatientId} }

func (m *ListVisitsArgs) IsNil() bool { return m == nil }

func (m *ListVisitsArgs) EncodeFields(w model.FieldWriter) {
	w.String("patient_id", m.PatientId)
}

func (m *ListVisitsArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("patient_id"); ok { m.PatientId = v }
}

type ListVisitsArgsList []*ListVisitsArgs

func (s *ListVisitsArgsList) Schema() []model.Field { return nil }
func (s *ListVisitsArgsList) Pointers() []any     { return nil }
func (s *ListVisitsArgsList) Len() int             { return len(*s) }
func (s *ListVisitsArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *ListVisitsArgsList) Append() model.Fielder  { v := &ListVisitsArgs{}; *s = append(*s, v); return v }
func (s *ListVisitsArgsList) IsNil() bool          { return s == nil }
func (s *ListVisitsArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *ListVisitsArgsList) DecodeFields(_ model.FieldReader) {}

func (m *ListVisitsArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

