// DO NOT EDIT. generated by github.com/tinywasm/orm

package clinical_encounter

import (
	"github.com/tinywasm/fmt"
	"github.com/tinywasm/orm"
)

func (m *MedicalHistory) ModelName() string {
	return "medical_history"
}

var _schemaMedicalHistory = []fmt.Field{
		{Name: "id", Type: fmt.FieldText, DB: &fmt.FieldDB{PK: true}},
		{Name: "patient_id", Type: fmt.FieldText, NotNull: true},
		{Name: "doctor_id", Type: fmt.FieldText, NotNull: true},
		{Name: "reservation_id", Type: fmt.FieldText},
		{Name: "status", Type: fmt.FieldText, NotNull: true},
		{Name: "attention_at", Type: fmt.FieldInt, NotNull: true},
		{Name: "reason", Type: fmt.FieldText, NotNull: true},
		{Name: "diagnostic", Type: fmt.FieldText},
		{Name: "prescription", Type: fmt.FieldText},
		{Name: "cie10_code", Type: fmt.FieldText},
		{Name: "started_at", Type: fmt.FieldInt},
		{Name: "finished_at", Type: fmt.FieldInt},
		{Name: "patient_name_snapshot", Type: fmt.FieldText, NotNull: true},
		{Name: "patient_rut_snapshot", Type: fmt.FieldText, NotNull: true},
		{Name: "doctor_name_snapshot", Type: fmt.FieldText, NotNull: true},
		{Name: "doctor_specialty_snapshot", Type: fmt.FieldText},
		{Name: "updated_at", Type: fmt.FieldInt, NotNull: true},
	}

func (m *MedicalHistory) Schema() []fmt.Field { return _schemaMedicalHistory }

func (m *MedicalHistory) Pointers() []any { return []any{&m.ID, &m.PatientID, &m.DoctorID, &m.ReservationID, &m.Status, &m.AttentionAt, &m.Reason, &m.Diagnostic, &m.Prescription, &m.Cie10Code, &m.StartedAt, &m.FinishedAt, &m.PatientNameSnapshot, &m.PatientRutSnapshot, &m.DoctorNameSnapshot, &m.DoctorSpecialtySnapshot, &m.UpdatedAt} }

type MedicalHistoryList []*MedicalHistory

func (s *MedicalHistoryList) Schema() []fmt.Field { return nil }
func (s *MedicalHistoryList) Pointers() []any     { return nil }
func (s *MedicalHistoryList) Len() int             { return len(*s) }
func (s *MedicalHistoryList) At(i int) fmt.Fielder { return (*s)[i] }
func (s *MedicalHistoryList) Append() fmt.Fielder  { v := &MedicalHistory{}; *s = append(*s, v); return v }

func (m *MedicalHistory) Validate(action byte) error {
	return fmt.ValidateFields(action, m)
}

func ReadOneMedicalHistory(qb *orm.QB, model *MedicalHistory) (*MedicalHistory, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllMedicalHistory(qb *orm.QB) (*MedicalHistoryList, error) {
	var results MedicalHistoryList
	err := qb.ReadAll(
		func() fmt.Model { return &MedicalHistory{} },
		func(m fmt.Model) { results = append(results, m.(*MedicalHistory)) },
	)
	return &results, err
}

func (m *CreateVisitArgs) ModelName() string {
	return "create_visit_args"
}

var _schemaCreateVisitArgs = []fmt.Field{
		{Name: "patient_id", Type: fmt.FieldText},
		{Name: "doctor_id", Type: fmt.FieldText},
		{Name: "attention_at", Type: fmt.FieldInt},
		{Name: "reason", Type: fmt.FieldText},
		{Name: "patient_name_snapshot", Type: fmt.FieldText},
		{Name: "patient_rut_snapshot", Type: fmt.FieldText},
		{Name: "doctor_name_snapshot", Type: fmt.FieldText},
		{Name: "reservation_id", Type: fmt.FieldText},
		{Name: "diagnostic", Type: fmt.FieldText},
		{Name: "prescription", Type: fmt.FieldText},
		{Name: "doctor_specialty_snapshot", Type: fmt.FieldText},
	}

func (m *CreateVisitArgs) Schema() []fmt.Field { return _schemaCreateVisitArgs }

func (m *CreateVisitArgs) Pointers() []any { return []any{&m.PatientID, &m.DoctorID, &m.AttentionAt, &m.Reason, &m.PatientNameSnapshot, &m.PatientRutSnapshot, &m.DoctorNameSnapshot, &m.ReservationID, &m.Diagnostic, &m.Prescription, &m.DoctorSpecialtySnapshot} }

type CreateVisitArgsList []*CreateVisitArgs

func (s *CreateVisitArgsList) Schema() []fmt.Field { return nil }
func (s *CreateVisitArgsList) Pointers() []any     { return nil }
func (s *CreateVisitArgsList) Len() int             { return len(*s) }
func (s *CreateVisitArgsList) At(i int) fmt.Fielder { return (*s)[i] }
func (s *CreateVisitArgsList) Append() fmt.Fielder  { v := &CreateVisitArgs{}; *s = append(*s, v); return v }

func ReadOneCreateVisitArgs(qb *orm.QB, model *CreateVisitArgs) (*CreateVisitArgs, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllCreateVisitArgs(qb *orm.QB) (*CreateVisitArgsList, error) {
	var results CreateVisitArgsList
	err := qb.ReadAll(
		func() fmt.Model { return &CreateVisitArgs{} },
		func(m fmt.Model) { results = append(results, m.(*CreateVisitArgs)) },
	)
	return &results, err
}

